In [1]:
#Define 2 number matrices; Multiply, add the matrices

In [2]:
import numpy as np

In [3]:
l = [1, 2, 3]
li = [4, 5, 6]
lis = [7, 8, 9]

matrix1 = np.matrix([l, li, lis])
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
t = [9, 8, 7]
ts = [6, 5, 4]
tsi = [3, 2, 1]

matrix2 = np.matrix([t, ts, tsi])
print(matrix2)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [5]:
if matrix1.shape == matrix2.shape:
    for i in range(len(matrix1)):
        print(matrix1[i] + matrix2[i])

[[10 10 10]]
[[10 10 10]]
[[10 10 10]]


In [6]:
if matrix1.shape == matrix2.shape:
    for i in range(len(matrix1)):
        for j in range(len(matrix2)):
            print(matrix1[i,j] * matrix2[i,j])

9
16
21
24
25
24
21
16
9


In [11]:
mat=[[1,2,3],
   [3,4,5]]
    
print(mat[1][1])

4


In [12]:
mm=np.matmul(matrix1,matrix2)
print(mm)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [7]:
#Define 2 string matrices, concatenate individual values

In [8]:
m = ['dra', 'pega', 'cer']
my = ['aira', 'goor', 'car']
myt = ['fen', 'chi', 'skolo']

matrix10 = np.matrix([m, my, myt])
print(matrix10)

[['dra' 'pega' 'cer']
 ['aira' 'goor' 'car']
 ['fen' 'chi' 'skolo']]


In [9]:
ma = ['nix', 'vata', 'corn']
mat = ['lin', 'baena', 'pendra']
matc = ['guari', 'cinus', 'chu']

matrix11 = np.matrix([ma, mat, matc])
print(matrix11)

[['nix' 'vata' 'corn']
 ['lin' 'baena' 'pendra']
 ['guari' 'cinus' 'chu']]


In [10]:
if matrix10.shape == matrix11.shape:
    for i in range(len(matrix10)):
        for j in range(len(matrix11)):
            print(str(matrix10[i,j]) + str(matrix11[i, j]))

dranix
pegavata
cercorn
airalin
goorbaena
carpendra
fenguari
chicinus
skolochu
